# Challenge 1

In this challenge you will be working on **Pokemon**. You will answer a series of questions in order to practice dataframe calculation, aggregation, and transformation.

![Pokemon](../images/pokemon.jpg)

Follow the instructions below and enter your code.

#### Import all required libraries.

In [1]:
# import libraries
import numpy as np
import pandas as pd
import re

#### Import data set.

Import data set `Pokemon` from Ironhack's database. Read the data into a dataframe called `pokemon`.

*Data set attributed to [Alberto Barradas](https://www.kaggle.com/abcsds/pokemon/)*

In [2]:
# import data set from Ironhack's database
pokemon = pd.read_csv("../Pokemon.csv", sep=",", index_col=False)
pokemon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   Total       800 non-null    int64
 5   HP          800 non-null    int64
 6   Attack      800 non-null    int64
 7   Defense     800 non-null    int64
 8   Sp. Atk     800 non-null    int64
 9   Sp. Def     800 non-null    int64
 10  Speed       800 non-null    int64
 11  Generation  800 non-null    int64
 12  Legendary   800 non-null    bool
dtypes: bool(1), int64(9), object(3)
memory usage: 75.9+ KB

#### Print first 10 rows of `pokemon`.

In [3]:
# your code here
pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

When you look at a data set, you often wonder what each column means. Some open-source data sets provide descriptions of the data set. In many cases, data descriptions are extremely useful for data analysts to perform work efficiently and successfully.

For the `Pokemon.csv` data set, fortunately, the owner provided descriptions which you can see [here](https://www.kaggle.com/abcsds/pokemon/home). For your convenience, we are including the descriptions below. Read the descriptions and understand what each column means. This knowledge is helpful in your work with the data.

| Column | Description |
| --- | --- |
| # | ID for each pokemon |
| Name | Name of each pokemon |
| Type 1 | Each pokemon has a type, this determines weakness/resistance to attacks |
| Type 2 | Some pokemon are dual type and have 2 |
| Total | A general guide to how strong a pokemon is |
| HP | Hit points, or health, defines how much damage a pokemon can withstand before fainting |
| Attack | The base modifier for normal attacks (eg. Scratch, Punch) |
| Defense | The base damage resistance against normal attacks |
| SP Atk | Special attack, the base modifier for special attacks (e.g. fire blast, bubble beam) |
| SP Def | The base damage resistance against special attacks |
| Speed | Determines which pokemon attacks first each round |
| Generation | Number of generation |
| Legendary | True if Legendary Pokemon False if not |

#### Obtain the distinct values across `Type 1` and `Type 2`.

Exctract all the values in `Type 1` and `Type 2`. Then create an array containing the distinct values across both fields.

In [4]:
# your code here
type1 = pokemon["Type 1"]
type1_distinct = type1.unique()
type1_distinct

array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
       'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
       'Dragon', 'Dark', 'Steel', 'Flying'], dtype=object)

In [5]:
type2 = pokemon["Type 2"]
type2_distinct = type2.unique()
type2_distinct

array(['Poison', nan, 'Flying', 'Dragon', 'Ground', 'Fairy', 'Grass',
       'Fighting', 'Psychic', 'Steel', 'Ice', 'Rock', 'Dark', 'Water',
       'Electric', 'Fire', 'Ghost', 'Bug', 'Normal'], dtype=object)

In [6]:
type_1_2_full = pokemon[["Type 1","Type 2"]]
type_1_2_full

      Type 1  Type 2
0      Grass  Poison
1      Grass  Poison
2      Grass  Poison
3      Grass  Poison
4       Fire     NaN
..       ...     ...
795     Rock   Fairy
796     Rock   Fairy
797  Psychic   Ghost
798  Psychic    Dark
799     Fire   Water

[800 rows x 2 columns]

In [7]:
type_1_2_full_array = np.array(type1,type2).reshape(2,400)
type_1_2_full_array

array([['Grass', 'Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire',
        'Fire', 'Fire', 'Water', 'Water', 'Water', 'Water', 'Bug', 'Bug',
        'Bug', 'Bug', 'Bug', 'Bug', 'Bug', 'Normal', 'Normal', 'Normal',
        'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Poison',
        'Poison', 'Electric', 'Electric', 'Ground', 'Ground', 'Poison',
        'Poison', 'Poison', 'Poison', 'Poison', 'Poison', 'Fairy',
        'Fairy', 'Fire', 'Fire', 'Normal', 'Normal', 'Poison', 'Poison',
        'Grass', 'Grass', 'Grass', 'Bug', 'Bug', 'Bug', 'Bug', 'Ground',
        'Ground', 'Normal', 'Normal', 'Water', 'Water', 'Fighting',
        'Fighting', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Psychic',
        'Psychic', 'Psychic', 'Psychic', 'Fighting', 'Fighting',
        'Fighting', 'Grass', 'Grass', 'Grass', 'Water', 'Water', 'Rock',
        'Rock', 'Rock', 'Fire', 'Fire', 'Water', 'Water', 'Water',
        'Electric', 'Electric', 'Normal', 'Normal', 'Normal', 'Water',
        'Water', 'Poison', 'Poison', 'Water', 'Water', 'Ghost', 'Ghost',
        'Ghost', 'Ghost', 'Rock', 'Psychic', 'Psychic', 'Water', 'Water',
        'Electric', 'Electric', 'Grass', 'Grass', 'Ground', 'Ground',
        'Fighting', 'Fighting', 'Normal', 'Poison', 'Poison', 'Ground',
        'Ground', 'Normal', 'Grass', 'Normal', 'Normal', 'Water',
        'Water', 'Water', 'Water', 'Water', 'Water', 'Psychic', 'Bug',
        'Ice', 'Electric', 'Fire', 'Bug', 'Bug', 'Normal', 'Water',
        'Water', 'Water', 'Water', 'Normal', 'Normal', 'Water',
        'Electric', 'Fire', 'Normal', 'Rock', 'Rock', 'Rock', 'Rock',
        'Rock', 'Rock', 'Normal', 'Ice', 'Electric', 'Fire', 'Dragon',
        'Dragon', 'Dragon', 'Psychic', 'Psychic', 'Psychic', 'Psychic',
        'Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water',
        'Water', 'Water', 'Normal', 'Normal', 'Normal', 'Normal', 'Bug',
        'Bug', 'Bug', 'Bug', 'Poison', 'Water', 'Water', 'Electric',
        'Fairy', 'Normal', 'Fairy', 'Fairy', 'Psychic', 'Psychic',
        'Electric', 'Electric', 'Electric', 'Electric', 'Grass', 'Water',
        'Water', 'Rock', 'Water', 'Grass', 'Grass', 'Grass', 'Normal',
        'Grass', 'Grass', 'Bug', 'Water', 'Water', 'Psychic', 'Dark',
        'Dark', 'Water', 'Ghost', 'Psychic', 'Psychic', 'Normal', 'Bug',
        'Bug', 'Normal', 'Ground', 'Steel', 'Steel', 'Fairy', 'Fairy',
        'Water', 'Bug', 'Bug', 'Bug', 'Bug', 'Bug', 'Dark', 'Normal',
        'Normal', 'Fire', 'Fire', 'Ice', 'Ice', 'Water', 'Water',
        'Water', 'Ice', 'Water', 'Steel', 'Dark', 'Dark', 'Dark',
        'Water', 'Ground', 'Ground', 'Normal', 'Normal', 'Normal',
        'Fighting', 'Fighting', 'Ice', 'Electric', 'Fire', 'Normal',
        'Normal', 'Electric', 'Fire', 'Water', 'Rock', 'Rock', 'Rock',
        'Rock', 'Psychic', 'Fire', 'Psychic', 'Grass', 'Grass', 'Grass',
        'Grass', 'Fire', 'Fire', 'Fire', 'Fire', 'Water', 'Water',
        'Water', 'Water', 'Dark', 'Dark', 'Normal', 'Normal', 'Bug',
        'Bug', 'Bug', 'Bug', 'Bug', 'Water', 'Water', 'Water', 'Grass',
        'Grass', 'Grass', 'Normal', 'Normal', 'Water', 'Water',
        'Psychic', 'Psychic', 'Psychic', 'Psychic', 'Bug', 'Bug',
        'Grass', 'Grass', 'Normal', 'Normal', 'Normal', 'Bug', 'Bug',
        'Bug', 'Normal', 'Normal', 'Normal', 'Fighting', 'Fighting',
        'Normal', 'Rock', 'Normal', 'Normal', 'Dark', 'Dark', 'Steel',
        'Steel', 'Steel', 'Steel', 'Steel', 'Steel', 'Fighting',
        'Fighting', 'Fighting', 'Electric', 'Electric', 'Electric',
        'Electric', 'Electric', 'Bug', 'Bug', 'Grass', 'Poison',
        'Poison', 'Water', 'Water', 'Water', 'Water', 'Water', 'Fire',
        'Fire', 'Fire', 'Fire', 'Psychic', 'Psychic', 'Normal', 'Ground',
        'Ground', 'Ground', 'Grass', 'Grass', 'Normal', 'Dragon',
        'Dragon', 'Normal', 'Poison', 'Rock', 'Rock', 'Water', 'Water',
        'Water', 'Water', 'Ground', 'Ground', 'Rock', 'Rock', 'Rock',
        'Rock', 'Water', 'Water', 'Normal', 'Normal', 'Ghost', 'Ghost',
        'Ghost', 'Ghost', 'Ghost', 'Grass', 'Psychic', 'Dark', 'Dark',
        'Psychic', 'Ice', 'Ice', 'Ice', 'Ice', 'Ice'],
       ['Ice', 'Water', 'Water', 'Water', 'Water', 'Water', 'Dragon',
        'Dragon', 'Dragon', 'Dragon', 'Steel', 'Steel', 'Steel', 'Steel',
        'Rock', 'Ice', 'Steel', 'Dragon', 'Dragon', 'Dragon', 'Dragon',
        'Water', 'Water', 'Ground', 'Ground', 'Dragon', 'Dragon',
        'Steel', 'Psychic', 'Psychic', 'Psychic', 'Psychic', 'Grass',
        'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water',
        'Water', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Bug',
        'Bug', 'Electric', 'Electric', 'Electric', 'Grass', 'Grass',
        'Rock', 'Rock', 'Rock', 'Rock', 'Bug', 'Bug', 'Bug', 'Bug',
        'Bug', 'Bug', 'Bug', 'Electric', 'Water', 'Water', 'Grass',
        'Grass', 'Water', 'Water', 'Normal', 'Ghost', 'Ghost', 'Normal',
        'Normal', 'Normal', 'Ghost', 'Dark', 'Normal', 'Normal',
        'Psychic', 'Poison', 'Poison', 'Steel', 'Steel', 'Rock',
        'Psychic', 'Normal', 'Normal', 'Ghost', 'Dragon', 'Dragon',
        'Dragon', 'Dragon', 'Normal', 'Fighting', 'Fighting', 'Fighting',
        'Ground', 'Ground', 'Poison', 'Poison', 'Poison', 'Poison',
        'Grass', 'Water', 'Water', 'Water', 'Grass', 'Grass', 'Grass',
        'Dark', 'Electric', 'Normal', 'Ground', 'Grass', 'Electric',
        'Fire', 'Fairy', 'Bug', 'Grass', 'Ice', 'Ground', 'Ice',
        'Normal', 'Psychic', 'Psychic', 'Rock', 'Ghost', 'Ice',
        'Electric', 'Electric', 'Electric', 'Electric', 'Electric',
        'Electric', 'Psychic', 'Psychic', 'Psychic', 'Steel', 'Water',
        'Fire', 'Normal', 'Ghost', 'Ghost', 'Psychic', 'Water', 'Water',
        'Dark', 'Grass', 'Grass', 'Normal', 'Psychic', 'Grass', 'Grass',
        'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water',
        'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Dark', 'Dark',
        'Grass', 'Grass', 'Fire', 'Fire', 'Water', 'Water', 'Psychic',
        'Psychic', 'Normal', 'Normal', 'Normal', 'Electric', 'Electric',
        'Rock', 'Rock', 'Rock', 'Psychic', 'Psychic', 'Ground', 'Ground',
        'Normal', 'Normal', 'Fighting', 'Fighting', 'Fighting', 'Water',
        'Water', 'Water', 'Fighting', 'Fighting', 'Bug', 'Bug', 'Bug',
        'Bug', 'Bug', 'Bug', 'Grass', 'Grass', 'Grass', 'Grass', 'Water',
        'Ground', 'Ground', 'Ground', 'Fire', 'Fire', 'Fire', 'Grass',
        'Bug', 'Bug', 'Dark', 'Dark', 'Psychic', 'Ghost', 'Ghost',
        'Water', 'Water', 'Rock', 'Rock', 'Poison', 'Poison', 'Dark',
        'Dark', 'Normal', 'Normal', 'Psychic', 'Psychic', 'Psychic',
        'Psychic', 'Psychic', 'Psychic', 'Water', 'Water', 'Ice', 'Ice',
        'Ice', 'Normal', 'Normal', 'Electric', 'Bug', 'Bug', 'Grass',
        'Grass', 'Water', 'Water', 'Water', 'Bug', 'Bug', 'Grass',
        'Grass', 'Steel', 'Steel', 'Steel', 'Electric', 'Electric',
        'Electric', 'Psychic', 'Psychic', 'Ghost', 'Ghost', 'Ghost',
        'Dragon', 'Dragon', 'Dragon', 'Ice', 'Ice', 'Ice', 'Bug', 'Bug',
        'Ground', 'Fighting', 'Fighting', 'Dragon', 'Ground', 'Ground',
        'Dark', 'Dark', 'Normal', 'Normal', 'Normal', 'Dark', 'Dark',
        'Fire', 'Bug', 'Dark', 'Dark', 'Dark', 'Bug', 'Bug', 'Steel',
        'Rock', 'Grass', 'Flying', 'Flying', 'Electric', 'Electric',
        'Dragon', 'Dragon', 'Ground', 'Ground', 'Dragon', 'Dragon',
        'Dragon', 'Water', 'Water', 'Normal', 'Normal', 'Bug', 'Grass',
        'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water',
        'Water', 'Normal', 'Normal', 'Normal', 'Fire', 'Fire', 'Bug',
        'Bug', 'Bug', 'Fire', 'Fire', 'Fairy', 'Fairy', 'Fairy', 'Grass',
        'Grass', 'Fighting', 'Fighting', 'Normal', 'Psychic', 'Psychic',
        'Psychic', 'Steel', 'Steel', 'Steel', 'Steel', 'Fairy', 'Fairy',
        'Fairy', 'Fairy', 'Dark', 'Dark', 'Rock', 'Rock', 'Poison',
        'Poison', 'Water', 'Water', 'Electric', 'Electric', 'Rock',
        'Rock', 'Rock', 'Rock', 'Fairy', 'Fighting', 'Electric', 'Rock',
        'Dragon', 'Dragon', 'Dragon', 'Steel', 'Ghost', 'Ghost', 'Ghost',
        'Ghost', 'Ghost', 'Ghost', 'Ghost', 'Ghost', 'Ghost', 'Ghost',
        'Ice', 'Ice', 'Flying', 'Flying', 'Fairy', 'Dark', 'Dragon',
        'Rock', 'Rock', 'Psychic', 'Psychic', 'Fire']], dtype=object)

In [8]:
type_1_2_distinct_array = np.unique(type_1_2_full_array)
type_1_2_distinct_array

array(['Bug', 'Dark', 'Dragon', 'Electric', 'Fairy', 'Fighting', 'Fire',
       'Flying', 'Ghost', 'Grass', 'Ground', 'Ice', 'Normal', 'Poison',
       'Psychic', 'Rock', 'Steel', 'Water'], dtype=object)

#### Cleanup `Name` that contain "Mega".

If you have checked out the pokemon names carefully enough, you should have found there are junk texts in the pokemon names which contain "Mega". We want to clean up the pokemon names. For instance, "VenusaurMega Venusaur" should be "Mega Venusaur", and "CharizardMega Charizard X" should be "Mega Charizard X".

In [9]:
# way 1
pokemon_name = pokemon["Name"].str.replace(".*Mega","Mega",regex=True)
pokemon["Name"] = pokemon_name

# test transformed data
pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,Mega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,Mega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

In [10]:
#way 2
def clean_name(x):
    return re.sub(".*Mega","Mega",x)

pokemon["Name"] = pokemon["Name"].apply(clean_name)

# test transformed data
pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,Mega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,Mega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

#### Create a new column called `A/D Ratio` whose value equals to `Attack` devided by `Defense`.

For instance, if a pokemon has the Attack score 49 and Defense score 49, the corresponding `A/D Ratio` is 49/49=1.

In [11]:
# your code here
pokemon["A/D Ratio"] = pokemon["Attack"]/pokemon["Defense"]
pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.000000
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.984127
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.987952
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.813008
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1.209302
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,0.666667
796,719,Mega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,1.454545
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,1.833333
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,2.666667
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,0.916667

#### Identify the pokemon with the highest `A/D Ratio`.

In [12]:
# your code here
pokemon["A/D Ratio"].max()

9.0

In [13]:
pokemon.sort_values(["A/D Ratio"],ascending=False)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.000000
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,4.500000
19,15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.750000
453,408,Cranidos,Rock,NaN,350,67,125,40,30,30,58,4,False,3.125000
348,319,Sharpedo,Water,Dark,460,70,120,40,95,40,95,3,False,3.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
616,555,DarmanitanZen Mode,Fire,Psychic,540,105,30,105,140,105,55,5,False,0.285714
103,95,Onix,Rock,Ground,385,35,45,160,30,45,70,1,False,0.281250
484,436,Bronzor,Steel,Psychic,300,57,24,86,24,86,23,4,False,0.279070
139,129,Magikarp,Water,NaN,200,20,10,55,15,20,80,1,False,0.181818
230,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False,0.043478

In [14]:
pokemon_highest_adratio_raw = pokemon[pokemon["A/D Ratio"].isin([9.0])]
pokemon_highest_adratio_raw

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.0

In [15]:
pokemon_highest_adratio_name = pokemon_highest_adratio_raw.iloc[0,1]
pokemon_highest_adratio_name

'DeoxysAttack Forme'

In [16]:
#method 2
pokemon_highest_adratio_raw2 = pokemon.loc[(pokemon["A/D Ratio"]==9.0)]
pokemon_highest_adratio_raw2

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.0

In [17]:
pokemon_highest_adratio_name2 = pokemon.iloc[429,1]
pokemon_highest_adratio_name2

'DeoxysAttack Forme'

#### Identify the pokemon with the lowest A/D Ratio.

In [18]:
# your code here
pokemon["A/D Ratio"].min()

0.043478260869565216

In [19]:
pokemon_lowest_adratio_raw = pokemon[pokemon["A/D Ratio"].isin([0.043478260869565216])]
pokemon_lowest_adratio_raw

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
230,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False,0.043478

In [20]:
pokemon_lowest_adratio_name = pokemon_lowest_adratio_raw.iloc[0,1]
pokemon_lowest_adratio_name

'Shuckle'

#### Create a new column called `Combo Type` whose value combines `Type 1` and `Type 2`.

Rules:

* If both `Type 1` and `Type 2` have valid values, the `Combo Type` value should contain both values in the form of `<Type 1> <Type 2>`. For example, if `Type 1` value is `Grass` and `Type 2` value is `Poison`, `Combo Type` will be `Grass-Poison`.

* If `Type 1` has valid value but `Type 2` is not, `Combo Type` will be the same as `Type 1`. For example, if `Type 1` is `Fire` whereas `Type 2` is `NaN`, `Combo Type` will be `Fire`.

In [21]:
# your code here
def combo_type(arg1,arg2):
    if arg1!="null" and arg2!="null":
        return f"{arg1}-{arg2}"
    elif arg1!="null" and arg2=="null":
        return f"{arg1}"

In [22]:
pokemon["Type 2"] = pokemon["Type 2"].fillna("null")
pokemon["Type 2"]

0      Poison
1      Poison
2      Poison
3      Poison
4        null
        ...
795     Fairy
796     Fairy
797     Ghost
798      Dark
799     Water
Name: Type 2, Length: 800, dtype: object

In [23]:
pokemon["Combo Type"] = pokemon.apply(lambda x: combo_type(x["Type 1"],x["Type 2"]), axis=1)
pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.000000,Grass-Poison
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.984127,Grass-Poison
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.987952,Grass-Poison
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.813008,Grass-Poison
4,4,Charmander,Fire,null,309,39,52,43,60,50,65,1,False,1.209302,Fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,0.666667,Rock-Fairy
796,719,Mega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,1.454545,Rock-Fairy
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,1.833333,Psychic-Ghost
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,2.666667,Psychic-Dark
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,0.916667,Fire-Water

#### Identify the pokemon whose `A/D Ratio` are among the top 5.

In [24]:
# your code here
pokemon_sorted = pokemon.sort_values(["A/D Ratio"],ascending=False).reset_index(drop=True) 
pokemon_sorted

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
0,386,DeoxysAttack Forme,Psychic,null,600,50,180,20,180,20,150,3,True,9.000000,Psychic
1,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,4.500000,Water-Dark
2,15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.750000,Bug-Poison
3,408,Cranidos,Rock,null,350,67,125,40,30,30,58,4,False,3.125000,Rock
4,319,Sharpedo,Water,Dark,460,70,120,40,95,40,95,3,False,3.000000,Water-Dark
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,555,DarmanitanZen Mode,Fire,Psychic,540,105,30,105,140,105,55,5,False,0.285714,Fire-Psychic
796,95,Onix,Rock,Ground,385,35,45,160,30,45,70,1,False,0.281250,Rock-Ground
797,436,Bronzor,Steel,Psychic,300,57,24,86,24,86,23,4,False,0.279070,Steel-Psychic
798,129,Magikarp,Water,null,200,20,10,55,15,20,80,1,False,0.181818,Water
799,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False,0.043478,Bug-Rock

In [25]:
pokemon_top5_adratio = pokemon_sorted.iloc[[0,1,2,3,4],[1]]
pokemon_top5_adratio

                 Name
0  DeoxysAttack Forme
1            Carvanha
2       Mega Beedrill
3            Cranidos
4            Sharpedo

#### For the 5 pokemon printed above, aggregate `Combo Type` and use a list to store the unique values.

Your end product is a list containing the distinct `Combo Type` values of the 5 pokemon with the highest `A/D Ratio`.

In [26]:
pokemon_top5_full = pokemon_sorted.loc[[0,1,2,3,4],["Name","Combo Type","A/D Ratio"]]
pokemon_top5_full

                 Name  Combo Type  A/D Ratio
0  DeoxysAttack Forme     Psychic      9.000
1            Carvanha  Water-Dark      4.500
2       Mega Beedrill  Bug-Poison      3.750
3            Cranidos        Rock      3.125
4            Sharpedo  Water-Dark      3.000

In [27]:
pokemon_top5_full_list=np.array(pokemon_top5_full).tolist()
pokemon_top5_full_list

[['DeoxysAttack Forme', 'Psychic', 9.0],
 ['Carvanha', 'Water-Dark', 4.5],
 ['Mega Beedrill', 'Bug-Poison', 3.75],
 ['Cranidos', 'Rock', 3.125],
 ['Sharpedo', 'Water-Dark', 3.0]]

In [28]:
#method 2 merge
pokemon_top5_ct = pokemon_sorted.loc[[0,1,2,3,4],["Name","Combo Type"]]
pokemon_top5_ct

                 Name  Combo Type
0  DeoxysAttack Forme     Psychic
1            Carvanha  Water-Dark
2       Mega Beedrill  Bug-Poison
3            Cranidos        Rock
4            Sharpedo  Water-Dark

In [29]:
pokemon_top5_rt = pokemon_sorted.loc[[0,1,2,3,4],["Name","A/D Ratio"]]
pokemon_top5_rt

                 Name  A/D Ratio
0  DeoxysAttack Forme      9.000
1            Carvanha      4.500
2       Mega Beedrill      3.750
3            Cranidos      3.125
4            Sharpedo      3.000

In [30]:
pokemon_top5_full2 = pd.merge(pokemon_top5_ct,pokemon_top5_rt)
pokemon_top5_full2

                 Name  Combo Type  A/D Ratio
0  DeoxysAttack Forme     Psychic      9.000
1            Carvanha  Water-Dark      4.500
2       Mega Beedrill  Bug-Poison      3.750
3            Cranidos        Rock      3.125
4            Sharpedo  Water-Dark      3.000

In [31]:
pokemon_top5_full_list2=np.array(pokemon_top5_full2).tolist()
pokemon_top5_full_list2

[['DeoxysAttack Forme', 'Psychic', 9.0],
 ['Carvanha', 'Water-Dark', 4.5],
 ['Mega Beedrill', 'Bug-Poison', 3.75],
 ['Cranidos', 'Rock', 3.125],
 ['Sharpedo', 'Water-Dark', 3.0]]

#### For each of the `Combo Type` values obtained from the previous question, calculate the mean scores of all numeric fields across all pokemon.

Your output should look like below:

![Aggregate](../images/aggregated-mean.png)

In [32]:
pokemon_sorted_top5_full_df = pokemon_sorted.loc[[0,1,2,3,4]]
pokemon_sorted_top5_full_df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
0,386,DeoxysAttack Forme,Psychic,null,600,50,180,20,180,20,150,3,True,9.000,Psychic
1,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,4.500,Water-Dark
2,15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.750,Bug-Poison
3,408,Cranidos,Rock,null,350,67,125,40,30,30,58,4,False,3.125,Rock
4,319,Sharpedo,Water,Dark,460,70,120,40,95,40,95,3,False,3.000,Water-Dark

In [33]:
pokemon_statistics_top5 = pokemon_sorted_top5_full_df._get_numeric_data()
pokemon_statistics_top5.index = pokemon_sorted_top5_full_df["Combo Type"]
pokemon_statistics_top5

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
Combo Type,,,,,,,,,,,
Psychic,386,600,50,180,20,180,20,150,3,True,9.000
Water-Dark,318,305,45,90,20,65,20,65,3,False,4.500
Bug-Poison,15,495,65,150,40,15,80,145,1,False,3.750
Rock,408,350,67,125,40,30,30,58,4,False,3.125
Water-Dark,319,460,70,120,40,95,40,95,3,False,3.000

In [34]:
pokemon_ct_top5_list = pokemon_sorted_top5_full_df["Combo Type"]
pokemon_ct_top5_list

0       Psychic
1    Water-Dark
2    Bug-Poison
3          Rock
4    Water-Dark
Name: Combo Type, dtype: object

In [35]:
pokemon_statistics = pokemon._get_numeric_data()
pokemon_statistics.index = pokemon["Combo Type"]
pokemon_statistics

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
Combo Type,,,,,,,,,,,
Grass-Poison,1,318,45,49,49,65,65,45,1,False,1.000000
Grass-Poison,2,405,60,62,63,80,80,60,1,False,0.984127
Grass-Poison,3,525,80,82,83,100,100,80,1,False,0.987952
Grass-Poison,3,625,80,100,123,122,120,80,1,False,0.813008
Fire,4,309,39,52,43,60,50,65,1,False,1.209302
...,...,...,...,...,...,...,...,...,...,...,...
Rock-Fairy,719,600,50,100,150,100,150,50,6,True,0.666667
Rock-Fairy,719,700,50,160,110,160,110,110,6,True,1.454545
Psychic-Ghost,720,600,80,110,60,150,130,70,6,True,1.833333
Psychic-Dark,720,680,80,160,60,170,130,80,6,True,2.666667
Fire-Water,721,600,80,110,120,130,90,70,6,True,0.916667

In [36]:
pokemon_statistics_full_top5 = pokemon_statistics[pokemon_statistics.index.isin(pokemon_ct_top5_list)]
pokemon_statistics_full_top5

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
Combo Type,,,,,,,,,,,
Bug-Poison,13,195,40,35,30,20,20,50,1,False,1.166667
Bug-Poison,14,205,45,25,50,25,25,35,1,False,0.500000
Bug-Poison,15,395,65,90,40,45,80,75,1,False,2.250000
Bug-Poison,15,495,65,150,40,15,80,145,1,False,3.750000
Bug-Poison,48,305,60,55,50,40,55,45,1,False,1.100000
...,...,...,...,...,...,...,...,...,...,...,...
Psychic,606,485,75,75,75,125,95,40,5,False,1.000000
Water-Dark,658,530,72,95,67,103,71,122,6,False,1.417910
Psychic,677,355,62,48,54,63,60,68,6,False,0.888889
Psychic,678,466,74,48,76,83,81,104,6,False,0.631579
Psychic,678,466,74,48,76,83,81,104,6,False,0.631579

In [37]:
pokemon_statistics_full_bug_poison = pokemon_statistics_full_top5.loc["Bug-Poison",:]
pokemon_bug_poison_mean = pokemon_statistics_full_bug_poison.mean()
pokemon_bug_poison_mean_df = pd.DataFrame(pokemon_bug_poison_mean).transpose()
pokemon_bug_poison_mean_df.index=["Bug-Poison"]

pokemon_statistics_full_water_dark = pokemon_statistics_full_top5.loc["Water-Dark",:]
pokemon_water_dark_mean = pokemon_statistics_full_water_dark.mean()
pokemon_water_dark_mean_df = pd.DataFrame(pokemon_water_dark_mean).transpose()
pokemon_water_dark_mean_df.index=["Water-Dark"]

pokemon_statistics_full_psychic = pokemon_statistics_full_top5.loc["Psychic",:]
pokemon_psychic_mean = pokemon_statistics_full_psychic.mean()
pokemon_psychic_mean_df = pd.DataFrame(pokemon_psychic_mean).transpose()
pokemon_psychic_mean_df.index=["Psychic"]

pokemon_statistics_full_rock = pokemon_statistics_full_top5.loc["Rock",:]
pokemon_rock_mean = pokemon_statistics_full_rock.mean()
pokemon_rock_mean_df = pd.DataFrame(pokemon_rock_mean).transpose()
pokemon_rock_mean_df.index=["Rock"]

pokemon_bug_poison_mean_df

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
Bug-Poison,199.166667,347.916667,53.75,68.333333,58.083333,42.5,59.333333,65.916667,2.333333,0.0,1.315989

In [38]:
pokemon_final_mean_df = pokemon_bug_poison_mean_df
pokemon_final_mean_df = pokemon_final_mean_df.append(pokemon_water_dark_mean_df).append(pokemon_psychic_mean_df).append(pokemon_rock_mean_df)
pokemon_final_mean_df

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
Bug-Poison,199.166667,347.916667,53.750000,68.333333,58.083333,42.500000,59.333333,65.916667,2.333333,0.000000,1.315989
Water-Dark,347.666667,493.833333,69.166667,120.000000,65.166667,88.833333,63.500000,87.166667,3.166667,0.000000,2.291949
Psychic,381.973684,464.552632,72.552632,64.947368,67.236842,98.552632,82.394737,78.868421,3.342105,0.236842,1.164196
Rock,410.111111,409.444444,67.111111,103.333333,107.222222,40.555556,58.333333,32.888889,3.888889,0.111111,1.260091

#### ANOTHER METHOD WITH GROUPBY

In [45]:
pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.000000,Grass-Poison
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.984127,Grass-Poison
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.987952,Grass-Poison
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.813008,Grass-Poison
4,4,Charmander,Fire,null,309,39,52,43,60,50,65,1,False,1.209302,Fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,0.666667,Rock-Fairy
796,719,Mega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,1.454545,Rock-Fairy
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,1.833333,Psychic-Ghost
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,2.666667,Psychic-Dark
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,0.916667,Fire-Water

In [49]:
#we want to make the df only with the combo types of the top 5 pokemon with the higest rate:
#firstly, we create the list of their combo type
pokemon_ct_top5_list_unique = pokemon_ct_top5_list.unique().tolist()
pokemon_ct_top5_list_unique

['Psychic', 'Water-Dark', 'Bug-Poison', 'Rock']

In [51]:
#secondly, we make this df
pokemon_df_top5_combotype_ratio = pokemon[pokemon["Combo Type"].isin(pokemon_ct_top5_list_unique)]
pokemon_df_top5_combotype_ratio

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
16,13,Weedle,Bug,Poison,195,40,35,30,20,20,50,1,False,1.166667,Bug-Poison
17,14,Kakuna,Bug,Poison,205,45,25,50,25,25,35,1,False,0.500000,Bug-Poison
18,15,Beedrill,Bug,Poison,395,65,90,40,45,80,75,1,False,2.250000,Bug-Poison
19,15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.750000,Bug-Poison
53,48,Venonat,Bug,Poison,305,60,55,50,40,55,45,1,False,1.100000,Bug-Poison
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,606,Beheeyem,Psychic,null,485,75,75,75,125,95,40,5,False,1.000000,Psychic
726,658,Greninja,Water,Dark,530,72,95,67,103,71,122,6,False,1.417910,Water-Dark
745,677,Espurr,Psychic,null,355,62,48,54,63,60,68,6,False,0.888889,Psychic
746,678,MeowsticMale,Psychic,null,466,74,48,76,83,81,104,6,False,0.631579,Psychic
747,678,MeowsticFemale,Psychic,null,466,74,48,76,83,81,104,6,False,0.631579,Psychic

In [60]:
pokemon_df_top5_groupby = pokemon_df_top5_combotype_ratio.groupby(["Combo Type"])
pokemon_df_top5_groupby

In [63]:
pokemon_df_top5_mean = pokemon_df_top5_groupby.mean().sort_values(by='A/D Ratio', ascending=False)
pokemon_df_top5_mean

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
Combo Type,,,,,,,,,,,
Water-Dark,347.666667,493.833333,69.166667,120.000000,65.166667,88.833333,63.500000,87.166667,3.166667,0.000000,2.291949
Bug-Poison,199.166667,347.916667,53.750000,68.333333,58.083333,42.500000,59.333333,65.916667,2.333333,0.000000,1.315989
Rock,410.111111,409.444444,67.111111,103.333333,107.222222,40.555556,58.333333,32.888889,3.888889,0.111111,1.260091
Psychic,381.973684,464.552632,72.552632,64.947368,67.236842,98.552632,82.394737,78.868421,3.342105,0.236842,1.164196